applications/department/urls.py
from django.urls import path
from . import views

app_name = 'department_app'

urlpatterns = [
    path('departments_list/',
         views.DepartmentListView.as_view(),
         name='departments_list'
         ),
    path('new_department/',
         views.NewDepartmentCreateView.as_view(),
         name='new_department'
         )

]

applications/employee/urls.py
from django.urls import path
from . import views

app_name = 'employee_app'

urlpatterns = [
    path(
        '',
        views.IndexTemplateView.as_view(),
        name='index'
    ),
    path(
        'employees/',
        views.EmployeeListView.as_view(),
        name='employees_list'
    ),
    path(
        'employee/<pk>',
        views.EmployeeDetailView.as_view(),
        name='employee_details'
    ),
    path(
        'employee_update/<pk>',
        views.EmployeeUpdateView.as_view(),
        name='employee_update'
    ),
    path(
        'employee_delete/<pk>',
        views.EmployeeDeleteView.as_view(),
        name='employee_delete'
    ),
    path(
        'employee_create/',
        views.EmployeeCreateView.as_view(),
        name='employee_create'
    ),
    path(
        'employees/<short_name>',
        views.EmployeesByDepartmentListView.as_view(),
        name='employees_by_department'
    ),
]

employees/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.department.urls')),
    re_path('', include('applications.employee.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/header.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'employee_app:index' %}">
            <img src="{% static 'img/django_image.png' %}" alt="" width="30" height="30">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'employee_app:index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page"
                        href="{% url 'employee_app:employees_list' %}">Employee
                        List</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page"
                        href="{% url 'department_app:departments_list' %}">Departments List</a>
                </li>
            </ul>
            <form>
                <a href="{% url 'employee_app:employee_create' %}" class="btn btn-outline-success">New
                    Employee</a>
                <a href="{% url 'department_app:new_department' %}" class="btn btn-outline-primary">New
                    Department</a>
            </form>
        </div>
    </div>
</nav>