applications/department/urls.py
from django.urls import path
from . import views

app_name = 'department_app'

urlpatterns = [
    path('departments_list/',
         views.DepartmentListView.as_view(),
         name='departments_list'
         ),
    path('new_department/',
         views.NewDepartmentCreateView.as_view(),
         name='new_department'
         )

]

applications/employee/urls.py
from django.urls import path
from . import views

app_name = 'employee_app'

urlpatterns = [
    path(
        '',
        views.IndexTemplateView.as_view(),
        name='index'
    ),
    path(
        'employees/',
        views.EmployeeListView.as_view(),
        name='employees_list'
    ),
    path(
        'employee/<pk>',
        views.EmployeeDetailView.as_view(),
        name='employee_details'
    ),
    path(
        'employee_update/<pk>',
        views.EmployeeUpdateView.as_view(),
        name='employee_update'
    ),
    path(
        'employee_delete/<pk>',
        views.EmployeeDeleteView.as_view(),
        name='employee_delete'
    ),
    path(
        'employee_create/',
        views.EmployeeCreateView.as_view(),
        name='employee_create'
    ),
    path(
        'employees/<short_name>',
        views.EmployeesByDepartmentListView.as_view(),
        name='employees_by_department'
    ),
]

employees/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.department.urls')),
    re_path('', include('applications.employee.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/department/models.py
from django.db import models

# Create your models here.


class Department(models.Model):
    """Model definition for Department."""

    name = models.CharField('Department Name', max_length=60, unique=True)
    short_name = models.CharField(
        'Department Acronym', max_length=30, unique=True)

    class Meta:
        """Meta definition for Department."""

        verbose_name = 'Department'
        verbose_name_plural = 'Departments'

    def __str__(self):
        """Unicode representation of Department."""
        return self.name

applications/department/forms.py
from django import forms


class DepartmentForm(forms.Form):
    """Department definition."""

    new_department_name = forms.CharField(max_length=60, widget=forms.TextInput(
        attrs={
            'class': 'form-control'
        }
    )
    )
    new_department_acronym = forms.CharField(max_length=60, widget=forms.TextInput(
        attrs={
            'class': 'form-control'
        }
    )
    )
    new_employee_name = forms.CharField(max_length=60, widget=forms.TextInput(
        attrs={
            'class': 'form-control'
        }
    )
    )
    new_employee_last_name = forms.CharField(max_length=60, widget=forms.TextInput(
        attrs={
            'class': 'form-control'
        }
    )
    )

applications/department/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from .models import Department
from applications.employee.models import Employee
from .forms import DepartmentForm
from django.views.generic import FormView, ListView

# Create your views here.


class DepartmentListView(ListView):
    model = Department
    template_name = "department/departments_list.html"
    context_object_name = 'departments'


class NewDepartmentCreateView(FormView):
    template_name = "department/new_department.html"
    form_class = DepartmentForm
    success_url = reverse_lazy("department_app:departments_list")

    def form_valid(self, form):
        new_department = Department(
            name=form.cleaned_data['new_department_name'],
            short_name=form.cleaned_data['new_department_acronym']
        )
        new_department.save()

        name = form.cleaned_data['new_employee_name']
        last_name = form.cleaned_data['new_employee_last_name']
        Employee.objects.create(
            name=name,
            last_name=last_name,
            job_name='1',
            department=new_department
        )

        return super(NewDepartmentCreateView, self).form_valid(form)

templates/department/departments_list.html
{% extends 'base.html' %}


{% block title %}
Department List
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <p class="h1 text-center mt-4 mb-4">Department List</p>
            <table class="table table-striped text-center">
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Name</th>
                        <th scope="col">Short Name</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for department in departments %}
                    <tr>
                        <th scope="row">{{department.id}}</th>
                        <td>{{department.name}}</td>
                        <td>{{department.short_name}}</td>
                        <td>
                            <a href="{% url 'employee_app:employees_by_department' department.short_name %}"
                                class="btn btn-info ml-1 mb-1">See
                                Employees</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}

templates/department/new_department.html
{% extends 'base.html' %}


{% block title %}
Department List
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}
<div class="container">
    <div class="row">
        <p class="h1 text-center">Department List</p>
        <div class="col-12">
            <form method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-success" type="submit"> Submit </button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}