applications/employee/urls.py
from django.urls import path
from . import views

app_name = 'employee_app'

urlpatterns = [
    path(
        '',
        views.IndexTemplateView.as_view(),
        name='index'
    ),
    path(
        'employees/',
        views.EmployeeListView.as_view(),
        name='employees_list'
    ),
    path(
        'employee/<pk>',
        views.EmployeeDetailView.as_view(),
        name='employee_details'
    ),
    path(
        'employee_update/<pk>',
        views.EmployeeUpdateView.as_view(),
        name='employee_update'
    ),
    path(
        'employee_delete/<pk>',
        views.EmployeeDeleteView.as_view(),
        name='employee_delete'
    ),
    path(
        'employee_create/',
        views.EmployeeCreateView.as_view(),
        name='employee_create'
    ),
    path(
        'employees/<short_name>',
        views.EmployeesByDepartmentListView.as_view(),
        name='employees_by_department'
    ),
]

employees/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.department.urls')),
    re_path('', include('applications.employee.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/employee/models.py
from django.db import models
from applications.department.models import Department

# Create your models here.


class Skills(models.Model):
    """Model definition for Skills."""

    skill = models.CharField('Skill', max_length=50)

    class Meta:
        """Meta definition for Skills."""

        verbose_name = 'Skill'
        verbose_name_plural = 'Skills'

    def __str__(self):
        """Unicode representation of Skills."""
        return self.skill


class Employee(models.Model):
    """Model definition for Employee."""

    JOB_CHOICES = (
        ('0', 'Technical Support'),
        ('1', 'Developer'),
        ('2', 'System Administrator'),
        ('3', 'Cloud Engineer'),
        ('4', 'Teacher'),
        ('5', 'General Services'),
        ('6', 'Student'),
        ('7', 'Other'),
    )

    name = models.CharField('First Name', max_length=60)
    last_name = models.CharField('Last Name', max_length=60)
    age = models.IntegerField('Age', null=True, blank=True)
    id_number = models.IntegerField(
        'ID Number', unique=True, blank=True, null=True)
    job_name = models.CharField('Job Name', max_length=60, choices=JOB_CHOICES)
    image = models.ImageField(
        'Employee Avatar', upload_to='employee', blank=True, null=True)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    skills = models.ManyToManyField(Skills)

    class Meta:
        """Meta definition for Employee."""

        verbose_name = 'Employee'
        verbose_name_plural = 'Employees'
        ordering = ['id']

    def __str__(self):
        """Unicode representation of Employee."""
        return str(self.id) + ' ' + self.name + ' ' + self.last_name

applications/employee/forms.py
from django import forms
from .models import Employee


class EmployeeForm(forms.ModelForm):
    """Form definition for Employee."""

    class Meta:
        """Meta definition for Employeeform."""

        model = Employee
        fields = ('__all__')
        widgets = {
            "name": forms.TextInput(
                attrs={
                    "class": "form-control"
                }
            ),
            "last_name": forms.TextInput(
                attrs={
                    "class": "form-control"
                }
            ),
            "age": forms.NumberInput(
                attrs={
                    "class": "form-control"
                }
            ),
            "id_number": forms.NumberInput(
                attrs={
                    "class": "form-control"
                }
            ),
            "job_name": forms.Select(
                attrs={
                    "class": "form-select",
                }
            ),
            "image": forms.FileInput(
                attrs={
                    "class": "form-control"
                }
            ),
            "department": forms.Select(
                attrs={
                    "class": "form-select"
                }
            ),
            "skills": forms.CheckboxSelectMultiple(),
        }

applications/employee/views.py
from multiprocessing import context
from venv import create
from .forms import EmployeeForm
from .models import Employee

from django.urls import reverse_lazy

from django.views.generic import (TemplateView,
                                  ListView,
                                  DetailView,
                                  UpdateView,
                                  DeleteView,
                                  CreateView
                                  )

# Create your views here.


class IndexTemplateView(TemplateView):
    template_name = "index.html"


class EmployeeListView(ListView):
    model = Employee
    template_name = "employee/employees_list.html"
    context_object_name = 'employees'

    def get_queryset(self):
        kword = self.request.GET.get('kword', '')
        queryset = Employee.objects.filter(
            name__icontains=kword
        )
        return queryset


class EmployeeDetailView(DetailView):
    model = Employee
    template_name = "employee/employee_details.html"
    context_object_name = 'employee'


class EmployeeUpdateView(UpdateView):
    model = Employee
    template_name = "employee/employee_update.html"
    form_class = EmployeeForm
    success_url = reverse_lazy('employee_app:employees_list')


class EmployeeDeleteView(DeleteView):
    model = Employee
    template_name = "employee/employee_delete.html"
    context_object_name = 'employee'
    success_url = reverse_lazy('employee_app:employees_list')


class EmployeeCreateView(CreateView):
    model = Employee
    template_name = "employee/employee_create.html"
    form_class = EmployeeForm
    success_url = reverse_lazy('employee_app:employees_list')


class EmployeesByDepartmentListView(ListView):
    model = Employee
    template_name = "employee/employees_by_department.html"
    context_object_name = 'employees'

    def get_queryset(self):
        department_short_name = self.kwargs['short_name']
        queryset = Employee.objects.filter(
            department__short_name=department_short_name
        )
        return queryset

templates/employee/employee_create.html
{% extends 'base.html' %}


{% block title %}
Employees List
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}

<div class="container">
    <div class="row justify-content-around">
        <p class="h1 mt-4 text-center">Register an Employee</p>
        <form method="POST" class="col-8" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-success">Submit</button>
        </form>

    </div>
</div>
{% endblock content %}

templates/employee/employee_delete.html
{% extends 'base.html' %}


{% block title %}
Employees List
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-8">
            <div class="card text-center mt-5">
                <div class="card-header">
                    <strong>Eliminar Usuario</strong>
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{employee.name}}
                        {{employee.last_name}}</h5>
                    <p class="card-text">¿Está seguro que desea eliminar este usuario?</p>
                    <form method="POST">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-danger">
                            Yeah! Let's Delete it!
                        </button>
                        <a href="{% url 'employee_app:employees_list' %}" class="btn btn-primary">Come Back!</a>
                    </form>

                </div>
                <div class="card-footer text-muted">
                    <span class="badge bg-info text-dark">
                        THINK BEFORE ACT
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/employee/employee_details.html
{% extends 'base.html' %}


{% block title %}
Employees List
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}
<div class="container">
    <div class="row">
        <div class="col-12 mt-5 d-flex justify-content-center">
            <div class="card" style="width: 18rem;">
                <img src="{{employee.image.url}}" class="card-img-top" alt="{{employee.name}}">
                <div class="card-body">
                    <h5 class="card-title">{{employee.name}} {{employee.last_name}}</h5>
                    <p class="card-text mt-3">
                        <strong>Job Name:</strong>
                        {{employee.get_job_name_display}}
                    </p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item"> <strong>ID Number:</strong> {{employee.id_number}}</li>
                    <li class="list-group-item"> <strong>Department:</strong> {{employee.department.name}}</li>
                    <li class="list-group-item">
                        <span class="badge badge bg-info text-dark">Skills</span>
                        <ul class="list-group list-group-flush">
                            {% for skill in employee.skills.all %}
                            <li class="list-group-item">{{skill.skill}}</li>
                            {% endfor %}
                        </ul>
                    </li>
                </ul>
                </li>
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/employee/employee_update.html
{% extends 'base.html' %}


{% block title %}
Employees List
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}

<div class="container">
    <div class="row justify-content-around">
        <p class="h1 mt-4 text-center">Employee Edit</p>
        <form method="POST" class="col-8">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-success">Actualizar</button>
        </form>

    </div>
</div>
{% endblock content %}

templates/employee/employees_by_department.html
{% extends 'base.html' %}


{% block title %}
Employees List
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}

<div class="container">
    <div class="row">
        <p class="h1 text-center mt-3">Employees List</p>
        <div class="col-12 mt-3">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Name</th>
                        <th scope="col">Last Name</th>
                        <th scope="col">ID Number</th>
                        <th scope="col">Job Name</th>
                    </tr>
                </thead>
                <tbody>
                    {% for employee in employees %}
                    <tr>
                        <th scope="row">{{employee.id}}</th>
                        <td>{{employee.name}}</td>
                        <td>{{employee.last_name}}</td>
                        <td>{{employee.id_number}}</td>
                        <!-- Usar unicamente cuando el campo es CHOICES -->
                        <td>{{employee.get_job_name_display}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock content %}

templates/employee/employees_list.html
{% extends 'base.html' %}


{% block title %}
Employees List
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}

<div class="container">
    <div class="row">
        <p class="h1 text-center mt-3">Employees List</p>
        <form action="" class="row g-2" method="GET">
            {% csrf_token %}
            <div class="col-8">
                <input type="text" id="kword" name="kword" class="form-control" placeholder="Buscar Empleado">
            </div>
            <div class="col-4">
                <button class="btn btn-primary" type="submit">Buscar empleado</button>
            </div>
        </form>
        <div class="col-12 mt-3">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Name</th>
                        <th scope="col">Last Name</th>
                        <th scope="col">ID Number</th>
                        <th scope="col">Job Name</th>
                        <th scope="col">Department Name</th>
                        <th scope="col">Skills</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for employee in employees %}
                    <tr>
                        <th scope="row">{{employee.id}}</th>
                        <td>{{employee.name}}</td>
                        <td>{{employee.last_name}}</td>
                        <td>{{employee.id_number}}</td>
                        <!-- Usar unicamente cuando el campo es CHOICES -->
                        <td>{{employee.get_job_name_display}}</td>
                        <!-- En caso contrario, se desestructura hasta acceder al valor que queremos -->
                        <td>{{employee.department.name}}</td>
                        <td>
                            {% for skill in employee.skills.all %}
                            <p>{{skill.id}}-{{skill.skill}}</p>

                            {% endfor %}
                        </td>
                        <td>
                            <a href="{% url 'employee_app:employee_details' employee.id %}"
                                class="btn btn-info ml-1 mb-1">Ver</a>
                            <a href="{% url 'employee_app:employee_update' employee.id %}"
                                class="btn btn-warning ml-1 mb-1">Editar</a>
                            <a href="{% url 'employee_app:employee_delete' employee.id %}"
                                class="btn btn-danger ml-1 mb-1">Eliminar</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock content %}